### PR TITLE
update headers and copyright information

### PR DESCRIPTION
**Pull request by nodiscc**
Authoring info obtained using `git shortlog -sne` and `git blame`
Headers are now uniformized (except indentation)

### CODE REVIEW

**Comment by az0** [comment]
Do you have any outstanding changes now in progress that could be merged soon? If not, I suggest to close this pull request and to proceed in smaller chunks. 

I am planning soon to rewrite some of the Git history which may require you to refork. Sorry for the inconvenience.

**Comment by nodiscc** [comment]
Sorry for taking so long; I added the changes you suggested in your comments, see https://github.com/nodiscc/cleanerml/commit/701821dd637cebaff2121a63f0169f62dee97177 https://github.com/nodiscc/cleanerml/commit/1d304593afedf17123e4ea6bf189e9cf987e3a3a. I think it's ok to merge now, more changes can be added later if needed.

This was interesting regarding proper licensing in a collaborative project, I think the best way to handle this is to delegate the work to an automated tool (I don't know any) that updates copyright information based on git history (in this case git _and_ svn history)

**Comment by nodiscc** [comment]
@az0 ping. Is it good to merge?

I thought you would be interested in the discussion at https://github.com/RequestPolicyContinued/requestpolicy/issues/607 which is about how/when to update copyright years.

**Comment by cfoellmann** [comment]
you should add a `CONTRIBUTING.md` like this https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/CONTRIBUTING.md
That will automatically add this notice:
`Please review the guidelines for contributing to this repository.`

SEE: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/new

**Comment by nodiscc** [comment]
@cfoellmann Hi, the copyright should be

```
BleachBit CleanerML
Copyright (C) 2009 Andrew Ziem
http://bleachbit.sourceforge.net
```

since 2009 is the year Andrew updated the cleaner template, then

```
some-program cleaner
Copyright (C) YEARS cleaner-author
Copyright (C) YEARS another-cleaner-author
```

where `YEARS` contains every year where the file has been updated by the author. Eg if the file has been created by author1 in 2011, then **substantially** edited (logic changes, new process...) in 2013 by himself, then edited by author2 in 2014, it should read

```
some-program cleaner
Copyright (C) 2011, 2013 author1
Copyright (C) 2014 author2
```

Anyway, in my opinion we should only ensure that every contributor is listed, and we don't care about the years. Changing years only means copyright will expire in 2063 instead of 2061 (https://en.wikipedia.org/wiki/Copyright_term). Is it important?

**Comment by az0** [comment]
@nodiscc : I agree the year is not as important as the name, but ideally both would be accurate.

**Comment by nodiscc** [comment]
@az0 This patch looks good. Should we merge it?

**Comment by cfoellmann** [comment]
I dont see anything wrong with this.
Could be merged if it is wanted.

**Comment by nodiscc** [comment]
I will merge this in the coming weeks.

**Comment by nodiscc** [comment]
Merged.

dc1c64d2f9964a1023b48bbded4c97b04f8abac2
a7b1a6a2c06745760e39d7b3bdca4c0f9218588d
9836c0e9c6e0d6a7a9d780848715480434746f6c
f01c07914de360944c6075232c47d62e46d905af

**Pull request closed without merging**
