### PR TITLE
Massive improvment of the SMPlayer-Cleaner

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
Sorry! I don't know how to solve this merge conflict!

**Comment by Tobias-B-Besemer** [comment]
One problem with the improved cleaner:
The last rule doesn't get executed, and I don't know why!

**Comment by az0** [comment]
About the merge conflict. A red flag is set of commits in this PR starts with XnView, which is unrelated. 

One option is to start a new fork. If not a new fork, then create a new branch from the upstream master. (The new fork does this also.) Then create one new branch for each new pull request, like one for smplayer. Then take your newest smplayer.xml and commit it to the clean branch, and then do the pull rquest. 

Does this help?

**Comment by Tobias-B-Besemer** [comment]
The first 9 commit do nothing. I reverted them and they just listed.
The problem is/was, that my first PR I did in the Master of the Fork... :-/
Now, I have one branch for each PR...
I tried to make a Pull where I deleted smplayer.xml, then made a new Pull with the new version... But (I guess) because I didn't made a commit to your Master in between, the changes got combined and I had the conflicts again... :-/
My suggestion would be, you just delete the old version of smplayer.xml (it's a old version from me), and then check my new version in.
As it seems that git have a problem with my changes (can't figure out, what's old & new?) I'm pretty sure that if I do a new PR, we will have this merge conflicts again...

**Comment by Tobias-B-Besemer** [comment]
OK, seems I can' just make a second Fork...

2019-02-16 01_30_28-comparing az0_master tobias-b-besemer_i2p az0_cleanerml - firefox nightly

...and I have some PR open with this one...

2019-02-16 01_41_52-pull requests az0_cleanerml - firefox nightly

-> Therefor I shouldn't delete this one...


I googled a bit and tried this one:
http://www.siliconfidential.com/articles/15-seconds-to-cleaner-git-history/

But unfortunately it doesn't help much...
Result is visible in PR #162 ...

**Comment by Tobias-B-Besemer** [comment]
I'm now getting in contact with the Support of GitHub to solve this issue...
...and I don't know why, but they seem to "know" already, with which Fork I have problems...

2019-02-16 02_22_26-contact github - firefox nightly

2019-02-16 02_27_43-contact github - firefox nightly

**Comment by Tobias-B-Besemer** [comment]
OK, my Master is now clean... :-)

**Comment by Tobias-B-Besemer** [comment]
This PR is now "obsolete" for me! I make a new one!

**Pull request closed without merging**
