### PR TITLE
Stable Cleaners - Nominations

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
I'm only just now recognized, that "Release" in "cleanerml" isn't a copy of the released cleaners in "bleachbit"... (!!!)

So here are my nominations for this "stable" folder...

The following cleaners are "stable", but there are bugs in BB that prevent them from function fully:
- biglybt (Environment Variables don't work)
- irfanview (BB can't handle Unicode-file)
- shadow_copies_more (command line tool don't work like expected)
- total_commander (special keys in INI-file break cleaner)

The other cleaners are "stable" and work fully:
- deepscan_more
- github_desktop
- i2p
- smplayer
- windows_recycle_bins_-_more

One cleaner got into the PR, but the XML-file isn't my stable version:
- total_commander

### CODE REVIEW

**Comment by az0** [comment]
Could you please try to fix the merge conflict? Or open one or more new PRs?

**Comment by Tobias-B-Besemer** [comment]
I spend a lot of time the last two days programing cleaners... improved nearly every cleaner I worked on so far... Did e.g. a lot of work to use existing BB Strings (translation)... so a lot of PR are coming! ;-)
IMHO, just set this PR back to later... When all new PR are checked in, we can come back to it and I fix it or make a new PR. :-)

**Comment by az0** [comment]
I propose to close this because of the current merge conflict and all the related pull requests in progress

**Comment by az0** [comment]
As you said, let's revisit later

**Comment by Tobias-B-Besemer** [comment]
Yes! OK!

**Pull request closed without merging**
