### PR TITLE
added spideroak cache cleaner for windows

### PR DESCRIPTION
**Pull request by cfoellmann**

### CODE REVIEW

**Comment by cfoellmann** [comment]
@az0 download_cache on linux?

**Comment by cfoellmann** [comment]
@az0 this is stable and should be considered for merge.
@theatre-x or @az0 can one of you add the download_cache on Linux?

**Comment by nodiscc** [comment]
@cfoellmann Is this cleaner working?

**Comment by cfoellmann** [comment]
I am not using SpiderOak anymore.

**Pull request merged**
