### PR TITLE
smart_switch_pc_and_kies

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by az0** [comment]
I didn't see a response to my review about glob vs file. It's not critical, but recent versions of BleachBit will throw a little warning to the console

**Comment by Tobias-B-Besemer** [comment]
I can't see a review about glob vs file...

You talk about this line?
`<action command="delete" search="glob" path="%ProgramData%\Samsung\Device Error Recovery\default-*.log"/>`

Sometime I figured out, that `walk.files` doesn't work with a wildcard...
I documented this here:
https://github.com/Tobias-B-Besemer/docs/blob/cleanerml-examples/_posts/cleanerml-examples.md#commanddelete-searchwalkfiles

Maybe this was because of issue #456... If so, I will change the cleaner and the docu!

**Comment by Tobias-B-Besemer** [comment]
Or is it that...
`<action command="delete" search="walk.files" path="%ProgramData%\Samsung\Device Error Recovery\default-*.log"/>`
...work, but...
`<action command="delete" search="walk.files" path="~/.opera/icons/*.gif"/>`
...not ???

This would be very "crazy" for me, as a cleaner writer/editor, that don't understand Python... :-/

Btw.: I should know that for https://github.com/bleachbit/bleachbit/pull/481.

**Comment by Tobias-B-Besemer** [comment]
And what's about a "*" at the end?
`<action command="delete" search="walk.files" path="$LocalAppData\Temp\AdobeARM*"/>`
Should know that for https://github.com/bleachbit/bleachbit/pull/476...

**Comment by Tobias-B-Besemer** [comment]
@az0, I still should get an answer, here. It's a very important question for the cleaners (seems I need to re-do all) and for the documentation...

What I don't get is, that I have documented, that...
`And this doesn't work, too.`
`<action command="delete" search="walk.all" path="%windir%\Temp\WER*.hdmp"/>`
`Use `glob` instead:`
`<action command="delete" search="glob" path="%windir%\Temp\WER*.hdmp"/>`

`This also doesn't work!`
`<action command="delete" search="walk.all" path="%windir%\Temp*\WER1.hdmp"/>`
`Use `glob` instead:`
`<action command="delete" search="glob" path="%windir%\Temp*\WER1.hdmp"/>`

...but you showed me now, that...
`<action command="delete" search="walk.all" path="%windir%\*\WER1.hdmp"/>`
...would work!

I'm confused!

**Comment by az0** [comment]
Sorry, are the four comments above still relevant? One reason I ask is we have had discussions in other PRs and issue tickets.

In your last comment I see you are using `walk.all` with a file path, but `walk.all` is designed to be passed only directories. This is[ documented](https://docs.bleachbit.org/doc/cleanerml.html).

>walk.all: matches all and directories files under a **_directory_**.

**Comment by Tobias-B-Besemer** [comment]
Ahhmmm... yes, still relevant! The last line was just an example and WER1.hdmp should be a directory...

What I understand so far:
- `search="file"` is for a single file, were "path" and "filename" must match exactly;
- `search="glob"` is for a file or path, were I can use e.g. wildcards.

What I seem to understand:
- `search="walk.all"` is for directories, were I can at least use a wildcard for a directory in the path.

What I still don't understand:
- `search="walk.all"`, does it work with e.g. a wildcard in the path, in a foldername?
- `search="walk.all"`, does wildcards work in the file-/directory-name at the end?
- Is `search="walk.all"` a variant of `search="glob"`, when its allow wildcards?
- Do the same rules about wildcards then match for `search="walk.files"`?
- Is therefor `search="walk.files"` a variant of `search="glob"`, too?

**Pull request merged**
