### PR TITLE
created markup for PokerTH

### PR DESCRIPTION
**Pull request by mikevainio**
If I am wasting your time, do tell. I have no idea if any of this is finding a purpose as it does in my Win boxes.

### CODE REVIEW

**Comment by nodiscc** [comment]
@mikevainio Please base your changes on the latest `master`. The easiest way is to re-clone the repository if you don't want to mess with git commands. You based your work on an old version and therefore it is unmergeable in the current form.

**Comment by az0** [comment]
These look interesting. To help the process of review, it helps to break up PR into smaller changes.

**Comment by mikevainio** [comment]
Keep in mind that while I can make changes to markup easily enough, using Github/Pull Requests is a process relatively alien to me. ie: You may understand what is going on, but I know I have only a slim thread of comprehension (my concept of developer tools is circa 1980s = my shared folder works for me so it must for you/github). I use it and am well aware I am doing/contributing something. I have made changes, if/when I have noticed that you have asked me to (maybe months late!). But I have no sense of accomplishing anything as I do not have the same capacity to appreciate if/when anything is accomplished via this facility.

**Comment by nodiscc** [comment]
Thank you for your work, basically the workflow with git (using the github interface) is as follows

1. Navigate to a file in this repository, eg. https://github.com/az0/cleanerml/blob/master/release/gthumb.xml
2. Click the edit (pen) icon in the top right corner, edit the file with your proposed changes, write a short commit message in the field below the file
3. Click `Propose file change`, then click `Create Pull Request`.
4. To edit another file, repeat the same process.

This ensures that every unrelated change lies in it's own patch/Pull Request. It makes the review easier, and allows to merge a small subset of changes without waiting for all other changes to be approved.

About comments in the file themselves (TODOs for later, remarks, etc), a convention has been proposed to used a `@note` entry in the header (not inline in the XML). This ensures that every file is consistent and that such comments can easily be found.

You can find an example standard file header in https://github.com/az0/cleanerml/blob/master/release/ansible.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
    BleachBit
    Copyright (C) 2011 Andrew Ziem
    http://www.bleachbit.org

    Cleaner for ansible by nodiscc
    Copyright © 2016 nodiscc

    @url https://ansible.com
    @tested ok 2.0.2.0-1, Debian Stretch
    @note an empty ~/.ansible/cp directory remains. safe to remove?

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
```

Multiple `@tested, @note` lines can be added.

**Comment by mikevainio** [comment]
ok, and i create new file from same start point
/master/release/newmarkup.xml to add likewise (re-adding the other
cleaners i made which have become out of sync).

**Comment by nodiscc** [comment]
See Pull Requests #112 #113 #114 #115 #116 #117 #118 #119 #120 #121 #123 #124 #125 #126. This is what I did:

```
cd release/
for i in akelpad dirmaster goldwave paintnet sketchupmake textsrch virtualdub virtualdub-scripts-and-sparse stuffit pokerth; do git checkout origin/pr/108 "$i".xml; git checkout -b "mikevainio-$i"; git commit --author 'mikevainio <dickmanitoba@gmail.com>' -m "add/improve $i cleaner, ref #108"; git checkout master; done
cd ../pending/
for i in 7-zip acdsee_pro handbrake fontconfig_mod1 ; git checkout origin/pr/108 "$i".xml; git checkout -b "mikevainio-$i"; git commit --author 'mikevainio <dickmanitoba@gmail.com>' -m "add/improve $i cleaner, ref #108"; git checkout master; done
```

**Pull request closed without merging**
