### PR TITLE
added some app and version info

### PR DESCRIPTION
**Pull request by cfoellmann**

### CODE REVIEW

**Comment by az0** [comment]
This has a merge conflict.

My opinion is "@app" is redundant to the label element and "@os" is redundant to the the "os=" attribute.  The "@link" could be useful.

**Comment by cfoellmann** [comment]
the xml attributes are programmatic parameters and the comments are for humans. I think adding good comments makes it a lot easier to maintain.

**Comment by cfoellmann** [comment]
rebased but lets keep this until we have discussed #89

**Comment by nodiscc** [comment]
@cfoellmann please check https://github.com/az0/cleanerml/pull/83

**Comment by nodiscc** [comment]
Please resubmit a PR following the instructions at https://github.com/az0/cleanerml#additional-information or reopen if you have any questions.

**Pull request closed without merging**
