### PR TITLE
BiglyBT

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
Should make https://github.com/bleachbit/bleachbit/pull/421 obsolete!

**Comment by Tobias-B-Besemer** [comment]
I saw you removed this cleaner again from the release...
Where there any problems with this cleaner ???

**Comment by Tobias-B-Besemer** [comment]
Seems this PR don't get together with the version you already have...
https://github.com/az0/cleanerml/blob/master/pending/biglybt.xml

**Comment by Tobias-B-Besemer** [comment]
If the other version if a old version from me, then you have removed my name and versioning?
Do you don't like it?
Should I let it out in future versions of cleaners?

**Comment by Tobias-B-Besemer** [comment]
I can remove my 'Credits' I add(ed) to my cleaners, but maybe you have a look at this wish from me: https://github.com/bleachbit/wishlist/issues/20

**Comment by Tobias-B-Besemer** [comment]
I'm willing to write a lot more cleaners (if you check them in) to push this project forward ('cause I like it), but I also wish to have some credits in any way (beside the stats of GitHub), to have credits of projects for future customers of my company...

**Comment by az0** [comment]
You asked about moving BiglyBT to this repository. I'd like to keep only major cleaners (like Google Chrome) there. I know this decision isn't retroactive, so there are already minor cleaners such as GL-117, which is not so popular.

You asked about removing credit. I didn't remove any of your comments. I moved the file verbatim. Here is the commit that removed it https://github.com/bleachbit/bleachbit/commit/b680b6d1d55aae4faf681a4a19e2897b4603090c

When I added committed the file here, I noted you as the author.

I encourage you to add your name (credit) to the individual cleaner .xml files as XML comments as you have been, if you wish. I'll elaborate more about credit in your other issue ticket about credits.

There is a merge conflict because it looks like you are adding a file, while I already added the file. To avoid the merge conflict, you'd want your fork to contain my commit that added the same file. In the future please avoid it, but for now I can manually merge it. 

Let me know if you think it's ready for merging. I looked at the difference, and it's basically OK. The new lint system will give you some notes about glob.

**Comment by Tobias-B-Besemer** [comment]
Thank you very much for your feedback! :-)

> Let me know if you think it's ready for merging. I looked at the difference, and it's basically OK. The new lint system will give you some notes about glob.

Sorry, I don't understand really this sentences (what you talk about)... But Cleaner is from my side "finished" and can be merged into your master.

**Comment by az0** [comment]
OK, I merged it https://github.com/az0/cleanerml/commit/bd09dc635c000ac482e3fd699a05e06229e489ee

**Comment by Tobias-B-Besemer** [comment]
Thx! :-)

**Pull request closed without merging**
