### PR TITLE
Initial Release

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**

### CODE REVIEW

**Comment by az0** [comment]
1: What is the benefit of deleting like this vs. what BleachBit normally does?

2: Is PotPlayer supposed to be in here?

**Comment by Tobias-B-Besemer** [comment]
1.) I thought it's cool to have it in CleanerML
+ I can't see what BB normally does, because I would have maybe troubles to red the code

2.) DAMN! NOPE! I copied the code from PP to start with, but seems to forgot to remove the last part!
-> I will make a new PR immediately!

**Comment by Tobias-B-Besemer** [comment]
Btw.: You provide no information with BB if you just delete the RC Bin on C:, or everywhere, and just for the user, or system wide...

**Comment by Tobias-B-Besemer** [comment]
@az0: Here was the conversation about benefits of my "I can do it - so why no"-Recycle-Bin-Cleaner... ;-)

**Pull request merged**
