### PR TITLE
extended steam

### PR DESCRIPTION
**Pull request by cfoellmann**
Missing stuff

### CODE REVIEW

**Comment by az0** [comment]
I appreciate you taking the time to submit this, and Steam is a popular application.  I also like that you documented your reference, which can be helpful for future research.

Because Winapp2.ini has unclear copyrights and is not licensed under the GNU General Public License, it is a dubious reference for cleaners for this repository.  This is basically notes #1 and #2 on [Submitting a cleaner.](http://bleachbit.sourceforge.net/contribute/cleaner). 

It is best to to inspecting the files and folders for yourself, and using a vendor's documentation should be OK too.

**Comment by cfoellmann** [comment]
It's not like you can license the path a program is installed in.
My code is mine since it is in no way a copy & paste.

I think there is no problem here. I found these paths like the others like you suggested

**Comment by nodiscc** [comment]
FWIW I agree with @cfoellmann 
I don't think you can copyright mere file paths. Copyright (as in intellectual property) can protect works that result form creative thought. @az0 I think https://en.wikipedia.org/wiki/Wikipedia:Copyright_in_lists makes sense (emphasis mine);

> Copyright in a list may exist in the content of the list or in the way that the content was selected and arranged. Copyright **does not protect facts**, but it does protect opinion.

What do you think?

**Comment by cfoellmann** [comment]
fixed

**Comment by tiemay** [comment]
@nodiscc I'm not sure file paths alone would be enough to qualify for copyright. Check out the copyright on [this photo](https://commons.wikimedia.org/wiki/File:Patreon_logo.svg). It reads:

*"This image only consists of simple geometric shapes and/or text. It does not meet the [threshold of originality](https://commons.wikimedia.org/wiki/Commons:Threshold_of_originality) needed for copyright protection, and is therefore in the [public domain](https://en.wikipedia.org/wiki/public_domain). Although it is free of copyright restrictions, this image may still be subject to [other restrictions](https://commons.wikimedia.org/wiki/Commons:Non-copyright_restrictions)."*

Other restrictions mainly being patents and trademarks. Though to be honest I'm somewhat lost in this conversation as to what was copied from who/where, and despite a possible exemption from copyright, I've been playing on the safe side by doing my own research, using vendor's documentation, and talking with developers for finding cleanable files.

**Comment by nodiscc** [comment]
@tiemay I think we agree. @cfoellmann based his cleaner on file paths he found at http://www.winapp2.com/downloads.html. While the winapp2.ini file has no copyright header or info (which makes it _all rights reserved_), I don't think ripping paths off this file is a copyright infringement because they are just that, factual, file paths.

I'd be very ok with merging this pull request, but of course @az0 you have the last word.

**Comment by cfoellmann** [comment]
@az0 this is stable and should be considered for merge.
I really dont understand the issue with the reference I gave. If you do not merge it because of it you can not provide cleaners that are in winapp2.ini ever.

Example to consider (maybe not really good):
Let's rename the 'Internet' because Microsoft has a Trademark on 'Internet Explorer'. :smiling_imp:

**Comment by Winapp2** [comment]
VirtualStore paths are sometimes created by Windows in the event that the UAC is active (and I think a non-administrator (possibly happens on admin accounts too - truthfully I've never checked)), creating a folder within the user's own profile to drop files into. They shouldn't be considered much different from the default paths, except that they're not always present on all systems.

**Comment by nodiscc** [comment]
@cfoellmann Is this still working?

**Comment by cfoellmann** [comment]
I am not using SpiderOak anymore.

**Pull request closed without merging**
